name: Ping Check

on:
  schedule:
    - cron: '*/5 * * * *'  # Dies führt die Action viertelstündlich aus

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Test
        id: ping
        run: |
          echo "${{ secrets.FRITZ_BOX_IP_ADRESS }}"
