name: Ping Check

on:
  schedule:
    - cron: '*/5 * * * *'  # Dies führt die Action viertelstündlich aus

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Test
        id: ping
        run: |
          ping -c 1 google.de > /dev/null 2>&1
          

