name: Ping Fritzbox

on:
  schedule:
    - cron: '*/5 * * * *'  

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Test
        id: ping
        run: |
          curl -k -sL -w "%{http_code}\\n" "${{ secrets.FRITZ_BOX_IP_ADRESS }}" 
          

